import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Shadcn/UI colors (HSL-based for theming)
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },

        // Design System colors (RGB-based for opacity)
        primary: "rgb(var(--color-primary-rgb))",
        "primary-light": "rgba(var(--color-primary-rgb), 0.1)",
        "primary-dark": "rgba(var(--color-primary-rgb), 0.9)",
        secondary: "rgb(var(--color-secondary-rgb))",
        success: "rgb(var(--color-success-rgb))",
        warning: "rgb(var(--color-warning-rgb))",
        danger: "rgb(var(--color-danger-rgb))",
        info: "rgb(var(--color-info-rgb))",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
      },
      fontSize: {
        xs: ["var(--text-xs)", { lineHeight: "var(--leading-tight)", letterSpacing: "var(--tracking-normal)" }],
        sm: ["var(--text-sm)", { lineHeight: "var(--leading-normal)", letterSpacing: "var(--tracking-normal)" }],
        base: ["var(--text-base)", { lineHeight: "var(--leading-normal)", letterSpacing: "var(--tracking-normal)" }],
        lg: ["var(--text-lg)", { lineHeight: "var(--leading-normal)", letterSpacing: "var(--tracking-tight)" }],
        xl: ["var(--text-xl)", { lineHeight: "var(--leading-relaxed)", letterSpacing: "var(--tracking-tight)" }],
        "2xl": ["var(--text-2xl)", { lineHeight: "var(--leading-relaxed)", letterSpacing: "var(--tracking-tighter)" }],
        "3xl": ["var(--text-3xl)", { lineHeight: "var(--leading-tight)", letterSpacing: "var(--tracking-tighter)" }],
        "4xl": ["var(--text-4xl)", { lineHeight: "var(--leading-tight)", letterSpacing: "var(--tracking-tighter)" }],
        "5xl": ["var(--text-5xl)", { lineHeight: "var(--leading-tight)", letterSpacing: "var(--tracking-tighter)" }],
        "6xl": ["var(--text-6xl)", { lineHeight: "var(--leading-tight)", letterSpacing: "var(--tracking-tighter)" }],
        "7xl": ["var(--text-7xl)", { lineHeight: "var(--leading-tight)", letterSpacing: "var(--tracking-tighter)" }],
        "8xl": ["var(--text-8xl)", { lineHeight: "var(--leading-tight)", letterSpacing: "var(--tracking-tighter)" }],
        "9xl": ["var(--text-9xl)", { lineHeight: "var(--leading-tight)", letterSpacing: "var(--tracking-tighter)" }],
      },
      fontWeight: {
        light: "var(--font-light)",
        regular: "var(--font-regular)",
        medium: "var(--font-medium)",
        semibold: "var(--font-semibold)",
        bold: "var(--font-bold)",
      },
      letterSpacing: {
        tighter: "var(--tracking-tighter)",
        tight: "var(--tracking-tight)",
        normal: "var(--tracking-normal)",
        wide: "var(--tracking-wide)",
        wider: "var(--tracking-wider)",
        widest: "var(--tracking-widest)",
      },
      lineHeight: {
        tight: "var(--leading-tight)",
        normal: "var(--leading-normal)",
        relaxed: "var(--leading-relaxed)",
      },
      spacing: {
        "0": "var(--spacing-0)",
        "px": "var(--spacing-px)",
        "0.5": "var(--spacing-0_5)",
        "1": "var(--spacing-1)",
        "2": "var(--spacing-2)",
        "3": "var(--spacing-3)",
        "4": "var(--spacing-4)",
        "5": "var(--spacing-5)",
        "6": "var(--spacing-6)",
        "8": "var(--spacing-8)",
        "10": "var(--spacing-10)",
        "12": "var(--spacing-12)",
        "16": "var(--spacing-16)",
        "20": "var(--spacing-20)",
        "24": "var(--spacing-24)",
        "32": "var(--spacing-32)",
        "40": "var(--spacing-40)",
        "48": "var(--spacing-48)",
        "56": "var(--spacing-56)",
        "64": "var(--spacing-64)",
      },
      boxShadow: {
        none: "var(--elevation-0)",
        sm: "var(--elevation-1)",
        DEFAULT: "var(--elevation-2)",
        md: "var(--elevation-3)",
        lg: "var(--elevation-4)",
        xl: "var(--elevation-5)",
        "2xl": "var(--elevation-6)",
      },
      borderRadius: {
        none: "var(--radius-none)",
        sm: "var(--radius-sm)",
        DEFAULT: "var(--radius-base)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        "3xl": "var(--radius-3xl)",
        full: "var(--radius-full)",
      },
      transitionTimingFunction: {
        "ease-out": "var(--ease-out)",
        "ease-in": "var(--ease-in)",
        "ease-in-out": "var(--ease-in-out)",
        "spring": "var(--ease-spring)",
        "bounce": "var(--ease-bounce)",
      },
      transitionDuration: {
        instant: "var(--duration-instant)",
        fast: "var(--duration-fast)",
        DEFAULT: "var(--duration-normal)",
        slow: "var(--duration-slow)",
        slower: "var(--duration-slower)",
        slowest: "var(--duration-slowest)",
      },
      zIndex: {
        dropdown: "var(--z-index-dropdown)",
        sticky: "var(--z-index-sticky)",
        fixed: "var(--z-index-fixed)",
        "modal-backdrop": "var(--z-index-modal-backdrop)",
        modal: "var(--z-index-modal)",
        popover: "var(--z-index-popover)",
        tooltip: "var(--z-index-tooltip)",
      },
      backdropBlur: {
        xs: "var(--glass-blur)",
      },
    },
  },
  plugins: [],
};

export default config;
